In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [13]:
brazi = pd.read_csv('dateBrazi.csv', sep = ';')
brazi.head()

Nr         UTC  Temperatura  Umiditate  VOC  eCO2     H2  Ethanol  \
0   0  1677693120       20.000      57.36    0   400  12306    18520   
1   1  1677693121       20.015      56.67    0   400  12345    18651   
2   2  1677693122       20.029      55.96    0   400  12374    18764   
3   3  1677693123       20.044      55.28    0   400  12390    18849   
4   4  1677693124       20.059      54.69    0   400  12403    18921   

   Presiunea  PM1.0  PM2.5  NC0.5  NC1.0  NC2.5  Alerta  
0    939.735    0.0    0.0    0.0    0.0    0.0       0  
1    939.744    0.0    0.0    0.0    0.0    0.0       0  
2    939.738    0.0    0.0    0.0    0.0    0.0       0  
3    939.736    0.0    0.0    0.0    0.0    0.0       0  
4    939.744    0.0    0.0    0.0    0.0    0.0       0

In [8]:
brazi.tail()

Nr         UTC  Temperatura  Umiditate  VOC  eCO2     H2  Ethanol  \
31025  62625  1677755745       18.438      15.79  625   400  13723    20569   
31026  62626  1677755746       18.653      15.87  612   400  13731    20588   
31027  62627  1677755747       18.867      15.84  627   400  13725    20582   
31028  62628  1677755748       19.083      16.04  638   400  13712    20566   
31029  62629  1677755749       19.299      16.52  643   400  13696    20543   

       Presiunea  PM1.0  PM2.5  NC0.5  NC1.0  NC2.5  Alerta  
31025    936.670   0.63   0.65   4.32  0.673  0.015       0  
31026    936.678   0.61   0.63   4.18  0.652  0.015       0  
31027    936.687   0.57   0.60   3.95  0.617  0.014       0  
31028    936.680   0.57   0.59   3.92  0.611  0.014       0  
31029    936.676   0.57   0.59   3.90  0.607  0.014       0

In [15]:
X = brazi.drop(['Nr', 'UTC', 'Alerta'] , axis=1)
y = brazi['Alerta']

In [16]:
X.head()

Temperatura  Umiditate  VOC  eCO2     H2  Ethanol  Presiunea  PM1.0  PM2.5  \
0       20.000      57.36    0   400  12306    18520    939.735    0.0    0.0   
1       20.015      56.67    0   400  12345    18651    939.744    0.0    0.0   
2       20.029      55.96    0   400  12374    18764    939.738    0.0    0.0   
3       20.044      55.28    0   400  12390    18849    939.736    0.0    0.0   
4       20.059      54.69    0   400  12403    18921    939.744    0.0    0.0   

   NC0.5  NC1.0  NC2.5  
0    0.0    0.0    0.0  
1    0.0    0.0    0.0  
2    0.0    0.0    0.0  
3    0.0    0.0    0.0  
4    0.0    0.0    0.0

In [17]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Alerta, dtype: int64

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [21]:
model_linear = SVC(kernel='linear')
model_linear.fit(X_train, y_train)

SVC(kernel='linear')

In [22]:
predictia = model_linear.predict(X_test)

In [23]:
matrice_confuzii = confusion_matrix(y_test, predictia)

In [24]:
matrice_confuzii

array([[1766,  749],
       [ 282, 6512]], dtype=int64)

In [25]:
print(classification_report(y_test, predictia))

              precision    recall  f1-score   support

           0       0.86      0.70      0.77      2515
           1       0.90      0.96      0.93      6794

    accuracy                           0.89      9309
   macro avg       0.88      0.83      0.85      9309
weighted avg       0.89      0.89      0.89      9309



In [26]:
model_polinom = SVC(kernel='poly', degree=3, C=1.0, coef0=1, gamma='scale')
model_polinom.fit(X_train, y_train)

SVC(coef0=1, kernel='poly')

In [32]:
predictia2 = model_polinom.predict(X_test)
matrice_confuzii2 = confusion_matrix(y_test, predictia2)
matrice_confuzii2

array([[1077, 1438],
       [   0, 6794]], dtype=int64)

In [33]:
print(classification_report(y_test, predictia2))

              precision    recall  f1-score   support

           0       1.00      0.43      0.60      2515
           1       0.83      1.00      0.90      6794

    accuracy                           0.85      9309
   macro avg       0.91      0.71      0.75      9309
weighted avg       0.87      0.85      0.82      9309



In [34]:
model_rbf = SVC(kernel='rbf', C=1.0, gamma='scale')
model_rbf.fit(X_train, y_train)

SVC()

In [35]:
predictia3 = model_rbf.predict(X_test)
matrice_confuzii3 = confusion_matrix(y_test, predictia3)
matrice_confuzii3

array([[1094, 1421],
       [   0, 6794]], dtype=int64)

In [36]:
print(classification_report(y_test, predictia3))

              precision    recall  f1-score   support

           0       1.00      0.43      0.61      2515
           1       0.83      1.00      0.91      6794

    accuracy                           0.85      9309
   macro avg       0.91      0.72      0.76      9309
weighted avg       0.87      0.85      0.82      9309

